require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'

Style/Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Exclude:
  - 'spec/**/*'

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - and

RSpec/FilePath:
  Enabled: false
