name: Test

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-22.04', 'ubuntu-latest', 'macos-latest']
        ruby: [3.2, 3.3, 3.4]
        experimental: [false]
        include:
          - os: 'ubuntu-latest'
            ruby: 'head'
            experimental: true
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ruby/setup-ruby@003a5c4d8d6321bd302e38f6f0ec593f77f06600 # v1.319.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: |
          bundle exec rake

  qlty:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ruby/setup-ruby@003a5c4d8d6321bd302e38f6f0ec593f77f06600 # v1.319.0
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - name: Test
        run: bundle exec rspec
      - uses: qltysh/qlty-action/coverage@08a0a862c159eae9b9003081da6663d96efef637 # v2.3.0
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: ./coverage/coverage.json
