name: Test

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-22.04', 'ubuntu-latest', 'macos-latest']
        ruby: [3.2, 3.3, 3.4]
        experimental: [false]
        include:
          - os: 'ubuntu-latest'
            ruby: 'head'
            experimental: true
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: |
          bundle exec rake

  qlty:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - name: Test
        run: bundle exec rspec
      - uses: qltysh/qlty-action/coverage@fd52dc852530a708d68c3b7342f8d33d1df4cd55 # v2.2.1
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: ./coverage/coverage.json
